# Site settings
title: David Bendet
email: dbendet@gmail.com
description: "Hey what's up."
baseurl: "www.davidbendet.com/"
url: "http://www.davidbendet.com"

# Build settings
markdown: kramdown
permalink: pretty
