# Site settings
title: David Bendet
email: dbendet@gmail.com
description: "This site is built in Jekyll.  Code here."
baseurl: ""
url: "http://davidbendet.com"

# Build settings
markdown: kramdown
permalink: pretty
